Removed apparently bogus defined(HAVE_C99_SNPRINTF) test. It was not AC_DEFINE'd in configure.in so it caused undefined reference to elinks_snprintf errors. Maybe it's time to at least take the time to compile before committing?