enum find_error: Add FIND_ERROR_MEMORY and FIND_ERROR_REGEX.
print_find_error: Print an appropriate message for FIND_ERROR_REGEX,
indicating a compilation failure for the regular expression.
Do not print anything for FIND_ERROR_MEMORY as a message box will take memory.

find_next_do: Return FIND_ERROR_MEMORY or FIND_ERROR_REGEX when
is_in_range returns -1 or -2, respectively.

find_next_do will now return FIND_ERROR_MEMORY
when the assertion in is_in_range fails. This design may be semantically
conspicuous, but it should not cause any problems as print_find_error
will not display a message for FIND_ERROR_MEMORY. I assume that
the message printed by assert() obviates any need for a message box.